// Patch 101b — replace every Twoleg house interior with an authored
// multi-room floor plan (rooms, cell-coord props, stairs for house-d).
// Marker-based splice: everything between `"rusty-house": {` and `  barn: {`
// is replaced. Assertion-guarded.
const fs = require("fs");
const p = "src/game/engine.ts";
let src = fs.readFileSync(p, "utf8");
const START = src.indexOf(`  "rusty-house": {`);
const END = src.indexOf(`  barn: {`);
if (START < 0 || END < 0 || END <= START) {
  console.error("patch101b: markers not found");
  process.exit(1);
}

const N = `  "rusty-house": {
    id: "rusty-house",
    name: "Rusty's Twoleg Nest",
    walls: roomWithDoor("bottom", 12),
    props: [
      // living room (north-west) / kitchen (north-east) / hall (south-west) / bedroom (south-east)
      { id: "rh-sofa", x: 4, y: 7, label: "Twoleg sleeping-soft (sofa)", style: "sofa" },
      { id: "rh-chair", x: 8, y: 6, label: "Twoleg perch (chair)", style: "chair" },
      { id: "rh-carpet", x: 10, y: 7, label: "Worn rug by the fire", style: "carpet" },
      { id: "rh-window", x: 2, y: 1, label: "Sunny window ledge", style: "window" },
      { id: "rh-lamp", x: 12, y: 2, label: "Glowing lamp", style: "lamp" },
      { id: "rh-books", x: 12, y: 7, label: "Twoleg leaf-clusters (books)", style: "books" },
      { id: "rh-counter", x: 16, y: 2, label: "Kitchen counter", style: "cabinet" },
      { id: "rh-coldbox", x: 19, y: 2, label: "The humming cold box", style: "cabinet" },
      { id: "rh-stove", x: 17, y: 5, label: "Warm stove", style: "stove" },
      { id: "rh-table", x: 19, y: 6, label: "Twoleg eating-table", style: "table" },
      { id: "rh-bowl", x: 4, y: 11, label: "Your food bowl", style: "bowl" },
      { id: "rh-bowl2", x: 6, y: 11, label: "Water bowl", style: "bowl" },
      { id: "rh-toy", x: 9, y: 12, label: "A woolly mouse toy", style: "toy" },
      { id: "rh-bed", x: 17, y: 11, label: "The Twolegs' big sleeping-nest", style: "bed" },
      { id: "rh-drawer", x: 20, y: 13, label: "Wooden drawers", style: "cabinet" },
    ],
    desc: "Warm, soft, and safe — and unbearably small. The Twolegs are out; the garden door is open.",
    rooms: [
      { name: "Rusty's Front Room", x0: 1, y0: 1, x1: 13, y1: 8 },
      { name: "Rusty's Kitchen", x0: 15, y0: 1, x1: 20, y1: 8 },
      { name: "Rusty's Hallway", x0: 1, y0: 10, x1: 13, y1: 14 },
      { name: "The Twolegs' Bedroom", x0: 15, y0: 10, x1: 20, y1: 14 },
    ],
    npcs: [],
  },
  "smudge-house": {
    id: "smudge-house",
    name: "Smudge's Cozy Home",
    walls: roomWithDoor("bottom", 12),
    props: [
      // living room (west) / kitchenette (east) over a full-width bedroom below
      { id: "sh-sofa", x: 3, y: 4, label: "Twoleg sofa", style: "sofa" },
      { id: "sh-carpet", x: 8, y: 3, label: "Thick soft carpet", style: "carpet" },
      { id: "sh-lamp", x: 14, y: 3, label: "Warm reading lamp", style: "lamp" },
      { id: "sh-window", x: 15, y: 1, label: "Window over the garden", style: "window" },
      { id: "sh-bowl", x: 13, y: 4, label: "Food bowl, always full", style: "bowl" },
      { id: "sh-bowl2", x: 14, y: 4, label: "Fresh water bowl", style: "bowl" },
      { id: "sh-bed", x: 4, y: 8, label: "Smudge's plush cat bed", style: "nest" },
      { id: "sh-toy", x: 7, y: 9, label: "Feather wand toy", style: "toy" },
      { id: "sh-toy2", x: 6, y: 8, label: "Catnip mouse", style: "toy" },
      { id: "sh-toy3", x: 8, y: 8, label: "Jingly ball", style: "toy" },
    ],
    desc: "Smudge's Twolegs dote on him. Toys everywhere, a plush bed, and the best view of the garden.",
    rooms: [
      { name: "Smudge's Living Room", x0: 1, y0: 1, x1: 11, y1: 5 },
      { name: "Smudge's Kitchen Nook", x0: 12, y0: 1, x1: 15, y1: 5 },
      { name: "Smudge's Bedroom", x0: 1, y0: 7, x1: 15, y1: 10 },
    ],
    npcs: ["smudge"],
  },
  "henry-house": {
    id: "henry-house",
    name: "Henry's House",
    walls: roomWithDoor("bottom", 12),
    props: [
      // kitchen (west) / living room (east) over a hall + bedroom
      { id: "hh-counter", x: 3, y: 2, label: "Kitchen counter", style: "cabinet" },
      { id: "hh-stove", x: 5, y: 2, label: "Polished stove", style: "stove" },
      { id: "hh-table", x: 7, y: 5, label: "Kitchen table", style: "table" },
      { id: "hh-sofa", x: 13, y: 4, label: "Firm upright sofa", style: "sofa" },
      { id: "hh-carpet", x: 14, y: 2, label: "Hearth rug", style: "carpet" },
      { id: "hh-shelf", x: 15, y: 1, label: "Twoleg shelf of curious objects", style: "shelf" },
      { id: "hh-post", x: 2, y: 10, label: "Tall scratching post", style: "post" },
      { id: "hh-bowl", x: 6, y: 9, label: "Food bowl", style: "bowl" },
      { id: "hh-bowl2", x: 8, y: 9, label: "Water bowl", style: "bowl" },
      { id: "hh-lamp", x: 9, y: 11, label: "Corner lamp", style: "lamp" },
      { id: "hh-bed", x: 14, y: 10, label: "Henry's large cat bed", style: "nest" },
    ],
    desc: "Henry's Twolegs keep a tidy house with a scratching post he is too dignified to use.",
    rooms: [
      { name: "Henry's Kitchen", x0: 1, y0: 1, x1: 9, y1: 6 },
      { name: "Henry's Living Room", x0: 11, y0: 1, x1: 16, y1: 6 },
      { name: "Henry's Hallway", x0: 1, y0: 8, x1: 11, y1: 11 },
      { name: "Henry's Bedroom", x0: 12, y0: 8, x1: 16, y1: 11 },
    ],
    npcs: ["henry"],
  },
  "princess-house": {
    id: "princess-house",
    name: "Princess's Sunny House",
    walls: roomWithDoor("bottom", 12),
    props: [
      // living room (west) / sunroom (east) over a bedchamber
      { id: "ph-chair", x: 3, y: 3, label: "Upholstered chair", style: "chair" },
      { id: "ph-window", x: 6, y: 1, label: "Wide sunny windowsill", style: "window" },
      { id: "ph-plant", x: 2, y: 1, label: "Houseplants (not for eating)", style: "moss" },
      { id: "ph-window2", x: 12, y: 1, label: "Sunroom glass, warm with light", style: "window" },
      { id: "ph-plant2", x: 13, y: 3, label: "Fern on a stand", style: "moss" },
      { id: "ph-bed2", x: 11, y: 3, label: "Sunroom napping cushion", style: "nest" },
      { id: "ph-bed", x: 3, y: 8, label: "Princess's cushioned bed", style: "nest" },
      { id: "ph-bowl", x: 6, y: 8, label: "Porcelain food bowl", style: "bowl" },
      { id: "ph-bowl2", x: 7, y: 8, label: "Porcelain water bowl", style: "bowl" },
      { id: "ph-carpet", x: 10, y: 8, label: "Pale delicate carpet", style: "carpet" },
      { id: "ph-shelf", x: 13, y: 7, label: "Shelves of twoleg ornaments", style: "shelf" },
      { id: "ph-toy", x: 12, y: 9, label: "A single dignified toy", style: "toy" },
    ],
    desc: "Bright, quiet, and full of sun. Princess's Twolegs keep an immaculate, gentle home.",
    rooms: [
      { name: "Princess's Living Room", x0: 1, y0: 1, x1: 8, y1: 4 },
      { name: "Princess's Sunroom", x0: 10, y0: 1, x1: 14, y1: 4 },
      { name: "Princess's Bedchamber", x0: 1, y0: 6, x1: 14, y1: 10 },
    ],
    npcs: ["princess"],
  },
  "marmalade-house": {
    id: "marmalade-house",
    name: "Marmalade's House",
    walls: roomWithDoor("bottom", 12),
    props: [
      // kitchen (west) / living room (east) over a hall + bedroom
      { id: "mh-counter", x: 3, y: 2, label: "Kitchen counter to spy from", style: "cabinet" },
      { id: "mh-stove", x: 6, y: 2, label: "Big warm stove", style: "stove" },
      { id: "mh-table", x: 8, y: 6, label: "Heavy wooden table", style: "table" },
      { id: "mh-sofa", x: 15, y: 4, label: "Dented old sofa", style: "sofa" },
      { id: "mh-box", x: 18, y: 2, label: "A twoleg box (his favorite)", style: "box" },
      { id: "mh-window", x: 19, y: 1, label: "Kitchen-garden window", style: "window" },
      { id: "mh-bowl", x: 3, y: 11, label: "Food bowl, licked clean", style: "bowl" },
      { id: "mh-bowl2", x: 5, y: 11, label: "Water bowl", style: "bowl" },
      { id: "mh-toy", x: 8, y: 12, label: "Chewed toy mouse", style: "toy" },
      { id: "mh-bed", x: 16, y: 11, label: "Marmalade's worn barn-style bed", style: "nest" },
      { id: "mh-blanket", x: 14, y: 12, label: "Piled blankets", style: "blanket" },
      { id: "mh-box2", x: 18, y: 12, label: "Another box (also his)", style: "box" },
    ],
    desc: "A big, busy kitchen-house. Marmalade rules it from the top of the table and naps in boxes.",
    rooms: [
      { name: "Marmalade's Kitchen", x0: 1, y0: 1, x1: 10, y1: 7 },
      { name: "Marmalade's Living Room", x0: 12, y0: 1, x1: 19, y1: 7 },
      { name: "The Back Hallway", x0: 1, y0: 9, x1: 10, y1: 13 },
      { name: "Marmalade's Bedroom", x0: 12, y0: 9, x1: 19, y1: 13 },
    ],
    npcs: ["marmalade"],
  },
  "ginger-house": {
    id: "ginger-house",
    name: "Ginger's House",
    walls: roomWithDoor("bottom", 12),
    props: [
      // kitchen (west) / living room (east) over a bedroom
      { id: "gh-counter", x: 2, y: 2, label: "Kitchen counter", style: "cabinet" },
      { id: "gh-stove", x: 4, y: 2, label: "Old ticking stove", style: "stove" },
      { id: "gh-bowl", x: 6, y: 3, label: "Food bowl", style: "bowl" },
      { id: "gh-bowl2", x: 7, y: 3, label: "Water bowl", style: "bowl" },
      { id: "gh-sofa", x: 11, y: 3, label: "Long sofa", style: "sofa" },
      { id: "gh-books", x: 14, y: 1, label: "Stacked twoleg scrolls (books)", style: "books" },
      { id: "gh-lamp", x: 9, y: 2, label: "Hallway lamp", style: "lamp" },
      { id: "gh-bed", x: 4, y: 8, label: "Ginger's traveling basket bed", style: "nest" },
      { id: "gh-toy", x: 8, y: 8, label: "Dangling feather toy", style: "toy" },
      { id: "gh-window", x: 12, y: 7, label: "Front-window perch", style: "window" },
      { id: "gh-carpet", x: 10, y: 9, label: "Bright patterned rug", style: "carpet" },
    ],
    desc: "A well-walked house with a view of the whole street — Ginger patrols it twice a day.",
    rooms: [
      { name: "Ginger's Kitchen", x0: 1, y0: 1, x1: 7, y1: 4 },
      { name: "Ginger's Living Room", x0: 9, y0: 1, x1: 14, y1: 4 },
      { name: "Ginger's Bedroom", x0: 1, y0: 6, x1: 14, y1: 10 },
    ],
    npcs: ["ginger"],
  },
  // ---------------------------------------------------------------------------
  // Twoleg house archetypes A-L. Genuinely different floor plans and
  // furnishings; props are authored on exact cell coordinates (cellProps).
  // ---------------------------------------------------------------------------
  "house-a": {
    id: "house-a",
    name: "A Snug Twoleg Nest",
    walls: roomWithDoor("bottom", 12),
    props: [
      // living room (west) / kitchen nook (east) over one bedroom
      { id: "ha-armchair", x: 3, y: 3, label: "Worn armchair", style: "chair" },
      { id: "ha-rug", x: 6, y: 3, label: "Round braided rug", style: "carpet" },
      { id: "ha-lamp", x: 2, y: 1, label: "Floor lamp", style: "lamp" },
      { id: "ha-counter", x: 11, y: 2, label: "Kitchen counter", style: "cabinet" },
      { id: "ha-counter2", x: 12, y: 3, label: "Cupboard with clinking dishes", style: "cabinet" },
      { id: "ha-bowl", x: 11, y: 4, label: "Kittypet food bowl", style: "bowl" },
      { id: "ha-bed", x: 5, y: 8, label: "Cushioned cat bed by the warmth", style: "nest" },
      { id: "ha-table", x: 9, y: 8, label: "Small eating-table", style: "table" },
      { id: "ha-toy", x: 11, y: 8, label: "Lost ball under the table", style: "toy" },
      { id: "ha-window", x: 2, y: 8, label: "Window over the yard", style: "window" },
    ],
    desc: "A small, warm nest. Twoleg scents of toast and laundry; a kettle ticks on the counter.",
    rooms: [
      { name: "The Front Room", x0: 1, y0: 1, x1: 9, y1: 4 },
      { name: "The Kitchen Nook", x0: 10, y0: 1, x1: 12, y1: 4 },
      { name: "The Back Room", x0: 1, y0: 6, x1: 12, y1: 9 },
    ],
    npcs: [],
  },
  "house-b": {
    id: "house-b",
    name: "A Grand Twoleg Nest",
    walls: roomWithDoor("bottom", 12),
    props: [
      // bedroom (north-west) / kitchen (north-east) / grand lounge (south) / dining (south-east)
      { id: "hb-bed", x: 4, y: 3, label: "Twoleg sleeping-nest (bed)", style: "bed" },
      { id: "hb-blanket", x: 6, y: 3, label: "Heaped blankets", style: "blanket" },
      { id: "hb-drawer", x: 8, y: 4, label: "Wooden drawers", style: "cabinet" },
      { id: "hb-counter", x: 15, y: 2, label: "Polished counter", style: "cabinet" },
      { id: "hb-cabinet", x: 20, y: 4, label: "Tall cabinet", style: "cabinet" },
      { id: "hb-bowl", x: 16, y: 5, label: "Food bowl", style: "bowl" },
      { id: "hb-bowl2", x: 17, y: 5, label: "Water bowl", style: "bowl" },
      { id: "hb-sofa", x: 5, y: 12, label: "Long velvet sofa", style: "sofa" },
      { id: "hb-sofa2", x: 9, y: 13, label: "Matching loveseat", style: "sofa" },
      { id: "hb-table", x: 7, y: 11, label: "Low table with a twoleg picture-box", style: "table" },
      { id: "hb-rug", x: 7, y: 12, label: "Huge soft rug", style: "carpet" },
      { id: "hb-table2", x: 17, y: 12, label: "Dining table", style: "table" },
      { id: "hb-lamp", x: 21, y: 10, label: "Standing lamp", style: "lamp" },
      { id: "hb-toy", x: 3, y: 10, label: "Cat tunnel of crinkly paper", style: "toy" },
    ],
    desc: "A big family nest — two sofas, a picture-box, and endless warm smells from the kitchen.",
    rooms: [
      { name: "The Master Bedroom", x0: 1, y0: 1, x1: 10, y1: 7 },
      { name: "The Kitchen", x0: 13, y0: 1, x1: 21, y1: 7 },
      { name: "The Grand Lounge", x0: 1, y0: 10, x1: 10, y1: 15 },
      { name: "The Dining Corner", x0: 14, y0: 10, x1: 21, y1: 15 },
    ],
    npcs: [],
  },
  "house-c": {
    id: "house-c",
    name: "An Old Twoleg Nest",
    walls: roomWithDoor("bottom", 12),
    props: [
      // storage room (north-west) / living room (north-east) / hall + back bedroom
      { id: "hc-box", x: 3, y: 3, label: "Stacked cardboard boxes", style: "box" },
      { id: "hc-box2", x: 5, y: 4, label: "Box with a cat-sized hole", style: "box" },
      { id: "hc-plant", x: 7, y: 2, label: "Leggy houseplant, half-wild", style: "moss" },
      { id: "hc-chair", x: 12, y: 3, label: "Broken-backed chair", style: "chair" },
      { id: "hc-lamp", x: 15, y: 2, label: "Flickering corner lamp", style: "lamp" },
      { id: "hc-cabinet", x: 15, y: 5, label: "Paint-peeling cabinet", style: "cabinet" },
      { id: "hc-dresser", x: 3, y: 9, label: "Scuffed old dresser", style: "cabinet" },
      { id: "hc-rug", x: 7, y: 9, label: "Faded threadbare rug", style: "carpet" },
      { id: "hc-bowl", x: 4, y: 11, label: "Chipped food bowl", style: "bowl" },
      { id: "hc-bowl2", x: 6, y: 11, label: "Stained water bowl", style: "bowl" },
      { id: "hc-bed", x: 13, y: 10, label: "A bed under a dust sheet", style: "bed" },
    ],
    desc: "A quiet old nest full of boxes and dust-shapes. Something small rustles behind the dresser.",
    rooms: [
      { name: "The Storage Room", x0: 1, y0: 1, x1: 8, y1: 5 },
      { name: "The Old Parlor", x0: 10, y0: 1, x1: 16, y1: 5 },
      { name: "The Main Hall", x0: 1, y0: 7, x1: 8, y1: 11 },
      { name: "The Back Bedroom", x0: 10, y0: 7, x1: 16, y1: 11 },
    ],
    npcs: [],
  },
  "house-d": {
    id: "house-d",
    name: "A Kittypet's Paradise",
    walls: roomWithDoor("bottom", 12),
    props: [
      // living room (west) / kitchen (east) over entry + dining; stairs to the bedrooms upstairs
      { id: "hd-tower", x: 3, y: 3, label: "Floor-to-ceiling cat tree", style: "post" },
      { id: "hd-post", x: 6, y: 2, label: "Second scratching post (well used)", style: "post" },
      { id: "hd-bed", x: 8, y: 4, label: "Round quilted cat bed", style: "nest" },
      { id: "hd-toy", x: 4, y: 5, label: "Pompoms in a basket", style: "toy" },
      { id: "hd-lamp", x: 2, y: 5, label: "Sunset-colored lamp", style: "lamp" },
      { id: "hd-counter", x: 15, y: 2, label: "Kitchen counter", style: "cabinet" },
      { id: "hd-coldbox", x: 18, y: 2, label: "Cold box full of fish-things", style: "cabinet" },
      { id: "hd-bowl", x: 16, y: 5, label: "Raised food bowl stand", style: "bowl" },
      { id: "hd-bowl2", x: 17, y: 5, label: "Water fountain, always running", style: "bowl" },
      { id: "hd-bed2", x: 18, y: 11, label: "Window-hammock bed", style: "nest" },
      { id: "hd-toy2", x: 15, y: 10, label: "Feather teaser on a stick", style: "toy" },
      { id: "hd-table", x: 17, y: 13, label: "Dining table", style: "table" },
      { id: "hd-blanket", x: 7, y: 11, label: "Pile of fleece blankets", style: "blanket" },
      { id: "hd-sofa", x: 3, y: 9, label: "Sofa with a cat-shaped dent", style: "sofa" },
    ],
    desc: "Every corner belongs to the cats here — towers, hammocks, a running water fountain, toys underfoot. A staircase climbs to the bedrooms.",
    rooms: [
      { name: "The Cat Parlor", x0: 1, y0: 1, x1: 10, y1: 6 },
      { name: "The Kitchen", x0: 14, y0: 1, x1: 18, y1: 6 },
      { name: "The Entry Hall", x0: 1, y0: 8, x1: 10, y1: 13 },
      { name: "The Dining Room", x0: 14, y0: 8, x1: 18, y1: 13 },
    ],
    stairs: [{ x: 3, y: 12, w: 2, h: 2, toX: 5, toY: 12, target: "house-d-up" }],
    npcs: [],
  },
  "house-d-up": {
    id: "house-d-up",
    name: "Upstairs Bedrooms",
    walls: roomWithDoor("bottom", 12),
    props: [
      // landing (west) / master bedroom (north-east) / child's room (mid-east) / bathroom (south-east)
      { id: "hdu-window", x: 2, y: 1, label: "Landing window over the street", style: "window" },
      { id: "hdu-bed", x: 14, y: 3, label: "The Twolegs' great bed", style: "bed" },
      { id: "hdu-cabinet", x: 17, y: 4, label: "Wardrobe", style: "cabinet" },
      { id: "hdu-lamp", x: 12, y: 4, label: "Bedside lamp", style: "lamp" },
      { id: "hdu-bed2", x: 14, y: 8, label: "A kitten's small bed", style: "bed" },
      { id: "hdu-toy", x: 16, y: 8, label: "Scattered toys", style: "toy" },
      { id: "hdu-box", x: 17, y: 7, label: "Toy chest", style: "box" },
      { id: "hdu-tub", x: 14, y: 12, label: "Big white water-tub", style: "tub" },
      { id: "hdu-toilet", x: 17, y: 12, label: "Twoleg water-seat", style: "toilet" },
      { id: "hdu-sink", x: 18, y: 10, label: "Wash-basin", style: "cabinet" },
    ],
    desc: "The quiet upstairs: two bedrooms, a kitten's room, and a bathroom full of strange water-things.",
    rooms: [
      { name: "The Upstairs Landing", x0: 1, y0: 1, x1: 8, y1: 13 },
      { name: "The Master Bedroom", x0: 10, y0: 1, x1: 18, y1: 5 },
      { name: "The Kitten's Room", x0: 10, y0: 7, x1: 18, y1: 9 },
      { name: "The Bathroom", x0: 10, y0: 11, x1: 18, y1: 13 },
    ],
    stairs: [{ x: 3, y: 11, w: 2, h: 2, toX: 5, toY: 13, target: "house-d" }],
    npcs: [],
  },
  "house-e": {
    id: "house-e",
    name: "A Sunny Twoleg Nest",
    walls: roomWithDoor("bottom", 12),
    props: [
      // kitchen (north-west) / sunroom (north-east) / bedroom (south-west) / reading den (south-east)
      { id: "he-counter", x: 3, y: 2, label: "Kitchen counter", style: "cabinet" },
      { id: "he-stove", x: 5, y: 2, label: "Warm stove", style: "stove" },
      { id: "he-table", x: 7, y: 5, label: "Breakfast table", style: "table" },
      { id: "he-window", x: 16, y: 1, label: "Sunroom glass, warm with light", style: "window" },
      { id: "he-window2", x: 19, y: 3, label: "Another wide pane", style: "window" },
      { id: "he-plant", x: 14, y: 3, label: "Potted fern", style: "moss" },
      { id: "he-plant2", x: 18, y: 5, label: "Tall palm in a clay pot", style: "moss" },
      { id: "he-chair", x: 16, y: 4, label: "Wicker sun chair", style: "chair" },
      { id: "he-bed", x: 4, y: 11, label: "First bedroom's bed", style: "bed" },
      { id: "he-nightstand", x: 7, y: 11, label: "Nightstand with a ticking clock", style: "cabinet" },
      { id: "he-bowl", x: 9, y: 9, label: "Food bowl by the hallway", style: "bowl" },
      { id: "he-bowl2", x: 10, y: 9, label: "Water bowl", style: "bowl" },
      { id: "he-books", x: 15, y: 11, label: "Twoleg leaf-clusters (books)", style: "books" },
      { id: "he-lamp", x: 17, y: 12, label: "Reading lamp", style: "lamp" },
    ],
    desc: "A bright nest with a glass sunroom. Dust motes drift over the bedrooms and a warm hallway.",
    rooms: [
      { name: "The Kitchen", x0: 1, y0: 1, x1: 9, y1: 6 },
      { name: "The Sunroom", x0: 13, y0: 1, x1: 19, y1: 6 },
      { name: "The Bedroom", x0: 1, y0: 8, x1: 9, y1: 13 },
      { name: "The Reading Den", x0: 13, y0: 8, x1: 19, y1: 13 },
    ],
    npcs: [],
  },
  "house-j": {
    id: "house-j",
    name: "A Quiet Twoleg Nest",
    walls: roomWithDoor("bottom", 12),
    props: [
      // kitchen (west) / living room (east) over hall + bedroom
      { id: "hj-counter", x: 3, y: 2, label: "Kitchen counter", style: "cabinet" },
      { id: "hj-stove", x: 5, y: 2, label: "Black stove", style: "stove" },
      { id: "hj-table", x: 7, y: 5, label: "Kitchen table", style: "table" },
      { id: "hj-sofa", x: 13, y: 4, label: "Sagging comfortable sofa", style: "sofa" },
      { id: "hj-carpet", x: 14, y: 2, label: "Worn sitting-rug", style: "carpet" },
      { id: "hj-window", x: 16, y: 1, label: "Window over the back garden", style: "window" },
      { id: "hj-post", x: 2, y: 10, label: "Well-clawed scratching post", style: "post" },
      { id: "hj-bowl", x: 5, y: 9, label: "Food bowl", style: "bowl" },
      { id: "hj-bowl2", x: 7, y: 9, label: "Water bowl", style: "bowl" },
      { id: "hj-bed", x: 14, y: 10, label: "Round cat bed", style: "nest" },
      { id: "hj-toy", x: 12, y: 11, label: "Springy toy", style: "toy" },
    ],
    desc: "A quiet, tidy nest. The clock on the wall ticks louder than anything else in the street.",
    rooms: [
      { name: "The Kitchen", x0: 1, y0: 1, x1: 8, y1: 6 },
      { name: "The Living Room", x0: 11, y0: 1, x1: 16, y1: 6 },
      { name: "The Hallway", x0: 1, y0: 8, x1: 11, y1: 11 },
      { name: "The Bedroom", x0: 12, y0: 8, x1: 16, y1: 11 },
    ],
    npcs: [],
  },
  "house-k": {
    id: "house-k",
    name: "A Cluttered Twoleg Nest",
    walls: roomWithDoor("bottom", 12),
    props: [
      // living room (west) / bedroom (center-east) / kitchen (south-center) / study (south-east)
      { id: "hk-sofa", x: 4, y: 3, label: "Deep old sofa", style: "sofa" },
      { id: "hk-rug", x: 7, y: 4, label: "Crooked rug", style: "carpet" },
      { id: "hk-window", x: 2, y: 1, label: "Window over the porch", style: "window" },
      { id: "hk-bed", x: 12, y: 3, label: "Unmade bed", style: "bed" },
      { id: "hk-drawer", x: 16, y: 3, label: "Overfull dresser", style: "cabinet" },
      { id: "hk-counter", x: 4, y: 9, label: "Kitchen counter", style: "cabinet" },
      { id: "hk-stove", x: 6, y: 9, label: "Stove with a whistling kettle", style: "stove" },
      { id: "hk-bowl", x: 11, y: 10, label: "Food bowl", style: "bowl" },
      { id: "hk-shelf", x: 16, y: 9, label: "Tall bookshelf", style: "shelf" },
      { id: "hk-books", x: 16, y: 11, label: "Stack of books", style: "books" },
      { id: "hk-chair", x: 13, y: 11, label: "Reading chair", style: "chair" },
    ],
    desc: "Books drift across every table and the sofa has swallowed many a lost sock.",
    rooms: [
      { name: "The Front Room", x0: 1, y0: 1, x1: 9, y1: 5 },
      { name: "The Bedroom", x0: 11, y0: 1, x1: 17, y1: 5 },
      { name: "The Kitchen", x0: 1, y0: 7, x1: 9, y1: 12 },
      { name: "The Study", x0: 15, y0: 7, x1: 17, y1: 12 },
    ],
    npcs: [],
  },
  "house-l": {
    id: "house-l",
    name: "A Roomy Twoleg Nest",
    walls: roomWithDoor("bottom", 12),
    props: [
      // kitchen (north-west) / living room (north-east) / dining (south-west) / bedroom (south-east)
      { id: "hl-counter", x: 3, y: 2, label: "Kitchen counter", style: "cabinet" },
      { id: "hl-stove", x: 5, y: 2, label: "Big stove", style: "stove" },
      { id: "hl-coldbox", x: 7, y: 2, label: "Humming cold box", style: "cabinet" },
      { id: "hl-sofa", x: 13, y: 3, label: "Wide family sofa", style: "sofa" },
      { id: "hl-table", x: 17, y: 4, label: "Low table", style: "table" },
      { id: "hl-window", x: 18, y: 1, label: "Picture window", style: "window" },
      { id: "hl-table2", x: 4, y: 11, label: "Dining table", style: "table" },
      { id: "hl-chair", x: 6, y: 12, label: "Dining chair", style: "chair" },
      { id: "hl-bowl", x: 9, y: 10, label: "Food bowl", style: "bowl" },
      { id: "hl-bed", x: 15, y: 11, label: "Twoleg bed", style: "bed" },
      { id: "hl-blanket", x: 17, y: 12, label: "Folded blankets", style: "blanket" },
      { id: "hl-toy", x: 11, y: 12, label: "Rolling twoleg ball", style: "toy" },
    ],
    desc: "A roomy nest with four good rooms and a kitchen that always smells of bread.",
    rooms: [
      { name: "The Kitchen", x0: 1, y0: 1, x1: 8, y1: 7 },
      { name: "The Living Room", x0: 11, y0: 1, x1: 18, y1: 7 },
      { name: "The Dining Room", x0: 1, y0: 9, x1: 12, y1: 13 },
      { name: "The Bedroom", x0: 14, y0: 9, x1: 18, y1: 13 },
    ],
    npcs: [],
  },
  // --- single-room cottages kept from the world-scale upgrade (smaller homes
  // on the street's edge): cozy, but not partitioned. ---
  "rusty-living": {
    id: "rusty-living",
    name: "Rusty's Front Room",
    desc: "Sunlight through lace curtains, a worn armchair, and a curled mat by the door.",
    walls: roomWithDoor("bottom", 12),
    props: [
      { id: "rl-carpet", x: 11, y: 9, label: "Worn rug by the fire", style: "carpet" },
      { id: "rl-sofa", x: 5, y: 6, label: "Twoleg sleeping-soft (sofa)", style: "sofa" },
      { id: "rl-chair", x: 8, y: 5, label: "Twoleg perch", style: "chair" },
      { id: "rl-table", x: 12, y: 5, label: "Twoleg eating-table", style: "table" },
      { id: "rl-cabinet", x: 17, y: 4, label: "Tall cabinet", style: "cabinet" },
      { id: "rl-lamp", x: 21, y: 5, label: "Glowing lamp", style: "lamp" },
      { id: "rl-blanket", x: 9, y: 14, label: "A curled sleeping mat", style: "blanket" },
      { id: "rl-toy", x: 15, y: 15, label: "A woolly mouse toy", style: "toy" },
      { id: "rl-bowl", x: 19, y: 13, label: "Food bowl", style: "bowl" },
      { id: "rl-plant", x: 22, y: 12, label: "Houseplant", style: "plant" },
    ],
  },
  "house-f": {
    id: "house-f",
    name: "Twoleg Living Room",
    desc: "A soft sofa faces a flickering box, and a rug warms the wooden floor.",
    walls: roomWithDoor("bottom", 12),
    props: [
      { id: "hf-sofa", x: 4, y: 6, label: "Soft sofa", style: "sofa" },
      { id: "hf-carpet", x: 10, y: 8, label: "Patterned rug", style: "carpet" },
      { id: "hf-lamp", x: 16, y: 4, label: "Standing lamp", style: "lamp" },
      { id: "hf-shelf", x: 20, y: 7, label: "Bookshelf", style: "shelf" },
      { id: "hf-box", x: 7, y: 12, label: "Cardboard box", style: "box" },
      { id: "hf-plant", x: 21, y: 13, label: "Houseplant", style: "plant" },
    ],
  },
  "house-g": {
    id: "house-g",
    name: "Twoleg Bedroom",
    desc: "A tall bed, a snoring Twoleg shape under blankets, and a wardrobe to hide behind.",
    walls: roomWithDoor("bottom", 12),
    props: [
      { id: "hg-bed", x: 4, y: 4, label: "Twoleg sleeping-nest", style: "bed" },
      { id: "hg-cabinet", x: 17, y: 4, label: "Wardrobe", style: "cabinet" },
      { id: "hg-lamp", x: 11, y: 13, label: "Bedside lamp", style: "lamp" },
      { id: "hg-box", x: 6, y: 14, label: "Storage box", style: "box" },
      { id: "hg-plant", x: 19, y: 12, label: "Houseplant", style: "plant" },
    ],
  },
  "house-h": {
    id: "house-h",
    name: "Twoleg Kitchen",
    desc: "Cold floor tiles, a towering cold box, and a bowl that smells faintly of fish.",
    walls: roomWithDoor("bottom", 12),
    props: [
      { id: "hh2-cabinet-1", x: 3, y: 4, label: "Kitchen counter", style: "cabinet" },
      { id: "hh2-cabinet-2", x: 9, y: 4, label: "Kitchen counter", style: "cabinet" },
      { id: "hh2-coldbox", x: 18, y: 4, label: "The humming cold box", style: "cabinet" },
      { id: "hh2-bowl-1", x: 12, y: 9, label: "Water bowl", style: "bowl" },
      { id: "hh2-bowl-2", x: 20, y: 12, label: "Food bowl", style: "bowl" },
      { id: "hh2-plant", x: 4, y: 12, label: "Window plant", style: "plant" },
    ],
  },
  "house-i": {
    id: "house-i",
    name: "Twoleg Study",
    desc: "Tall shelves of paper-filled leaves and a warm lamp burning late.",
    walls: roomWithDoor("bottom", 12),
    props: [
      { id: "hi-shelf-1", x: 3, y: 4, label: "Tall bookshelf", style: "shelf" },
      { id: "hi-shelf-2", x: 9, y: 4, label: "Tall bookshelf", style: "shelf" },
      { id: "hi-books", x: 15, y: 5, label: "Stack of books", style: "books" },
      { id: "hi-chair", x: 10, y: 10, label: "Reading chair", style: "chair" },
      { id: "hi-lamp", x: 17, y: 12, label: "Desk lamp", style: "lamp" },
    ],
  },
`;

src = src.slice(0, START) + N + src.slice(END);
fs.writeFileSync(p, src);
console.log("patch101b OK — authored house interiors installed");
